# Generated by Django 6.0.6 on 2026-06-19 13:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('data', models.DateTimeField()),
                ('luogo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_utente', models.CharField(choices=[('studente', 'Studente'), ('docente', 'Docente')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_docente', models.CharField(max_length=20, unique=True)),
                ('dipartimento', models.CharField(max_length=100)),
                ('ambito_ricerca', models.CharField(blank=True, max_length=200)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo_docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='catalogo.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('anno_pubblicazione', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('autori', models.ManyToManyField(related_name='libri', to='catalogo.autore')),
            ],
        ),
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(max_length=30, unique=True)),
                ('stato', models.CharField(choices=[('disponibile', 'Disponibile'), ('prestata', 'Prestata'), ('non_accessibile', 'Non accessibile')], default='disponibile', max_length=20)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copie', to='catalogo.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(max_length=100)),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinati', to='catalogo.personale')),
            ],
        ),
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateField(auto_now_add=True)),
                ('data_restituzione_prevista', models.DateField()),
                ('data_restituzione_effettiva', models.DateField(blank=True, null=True)),
                ('copia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestiti', to='catalogo.copia')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestiti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField()),
                ('commento', models.TextField(blank=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='catalogo.libro')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=20, unique=True)),
                ('corso_laurea', models.CharField(max_length=100)),
                ('anno_iscrizione', models.IntegerField()),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo_studente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
