# Generated by Django 6.0.6 on 2026-06-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autore',
            options={'verbose_name': 'Autore', 'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='copia',
            options={'verbose_name': 'Copia', 'verbose_name_plural': 'Copie'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docenti'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventi'},
        ),
        migrations.AlterModelOptions(
            name='iscrizione',
            options={'verbose_name': 'Iscrizione', 'verbose_name_plural': 'Iscrizioni'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libri'},
        ),
        migrations.AlterModelOptions(
            name='personale',
            options={'verbose_name': 'Membro dello staff', 'verbose_name_plural': 'Personale'},
        ),
        migrations.AlterModelOptions(
            name='prestito',
            options={'verbose_name': 'Prestito', 'verbose_name_plural': 'Prestiti'},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'verbose_name': 'Recensione', 'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AlterModelOptions(
            name='studente',
            options={'verbose_name': 'Studente', 'verbose_name_plural': 'Studenti'},
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
